# Generated by Django 4.2.13 on 2024-07-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="database",
            name="password",
            field=models.TextField(max_length=70),
        ),
    ]
